### PR TITLE
bitswap/httpnet: fix peers silently stopping from doing http requests

### LINKED ISSUE #979: bitswap/httpnet: http client hangs
I am observing an issue in Rainbow where http seems to hang and completely stop working from a certain point.

Restarting fixes it.

The logs show: `connect request to...`, which corresponds to attempting to connect to an endpoint using the pingCid url.

However, no connection is established. There is no further logging, nothing indicating a failure to connect or that even the request returns. It would seem as if the request is queued somewhere inside go http2 library and never returns.

I will debug further and leave notes here.

### PR DESCRIPTION
**Pull request by hsanjuan**
Fixes #979 (hopefully). If connectivity status has been switched from Connected without doing an httpnet DisconnectFrom(), it may be that we keep pinging the peers, and think we are connected to them, but never restore the connectivity status when skipping the connectivity checks (because we are connected). This results in silent, successful "Connect()" requests that do nothing.

### CODE REVIEW

File: bitswap/network/httpnet/httpnet.go [hunk 1]
```diff
@@ -508,7 +513,7 @@ func (ht *Network) Connect(ctx context.Context, pi peer.AddrInfo) error {
 		err = ht.connectToURL(ctx, pi.ID, u, "GET")
 		if err != nil {
 			errs = append(errs, fmt.Errorf("%s: %s", u.Multiaddress.String(), err))
```
Comment (gammazero) [inline bitswap/network/httpnet/httpnet.go:515]: Note: You could also use multierr.Append here.
```suggestion
			errs = multierr.Append(errs, fmt.Errorf("%s: %s", u.Multiaddress.String(), err))
```
Then `errs` would be declared as :
```
errs := ErrNoSuccess
```

**Review by gammazero — APPROVED** [review]

File: bitswap/network/httpnet/httpnet.go (hunk 1 above)
Comment (hsanjuan) [reply bitswap/network/httpnet/httpnet.go:515]: will fix next time I touch this code

Comment (hsanjuan) [reply bitswap/network/httpnet/httpnet.go:515]: ah wait, I think it is done this way because multierr.Append prints errors in a different way than multierr.Combine. The former joins them in a single line, and the latter nicely formats them in multiple lines. (IIRC!)
